// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx06pIVFXKcmPibgUAjHt52jrwin11bhI',
    appId: '1:257069213354:web:186fd60fcc8e1a3ab892d3',
    messagingSenderId: '257069213354',
    projectId: 'flutter-projet-7a82b',
    authDomain: 'flutter-projet-7a82b.firebaseapp.com',
    storageBucket: 'flutter-projet-7a82b.firebasestorage.app',
    measurementId: 'G-HGNV80DNLM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNtsS7zjiLESvP-yNrjlFsVZrPxA9-qdo',
    appId: '1:257069213354:android:7a817ff430c5c2a7b892d3',
    messagingSenderId: '257069213354',
    projectId: 'flutter-projet-7a82b',
    storageBucket: 'flutter-projet-7a82b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvb5Qg4bJh5K5Tvxk_7wagOa7fDswDCGE',
    appId: '1:257069213354:ios:da744d1a2cd4a78eb892d3',
    messagingSenderId: '257069213354',
    projectId: 'flutter-projet-7a82b',
    storageBucket: 'flutter-projet-7a82b.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvb5Qg4bJh5K5Tvxk_7wagOa7fDswDCGE',
    appId: '1:257069213354:ios:da744d1a2cd4a78eb892d3',
    messagingSenderId: '257069213354',
    projectId: 'flutter-projet-7a82b',
    storageBucket: 'flutter-projet-7a82b.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCx06pIVFXKcmPibgUAjHt52jrwin11bhI',
    appId: '1:257069213354:web:f3b1ff5be92d705bb892d3',
    messagingSenderId: '257069213354',
    projectId: 'flutter-projet-7a82b',
    authDomain: 'flutter-projet-7a82b.firebaseapp.com',
    storageBucket: 'flutter-projet-7a82b.firebasestorage.app',
    measurementId: 'G-5VW1YDYWLK',
  );
}
